### PR TITLE
Updated Index.HTML with required Bootstrap links and added starter Modal

### PR DESCRIPTION
**Pull request by molano1979**
Thank you Ben

### CODE REVIEW

**Review by corhydare — COMMENTED** [review]
looks good

**Review by corhydare — DISMISSED** [review]

**Review by PastaShock — DISMISSED** [review]
Looks good!

**Review by corhydare — DISMISSED** [review]
thank you

**Review by molano1979 — COMMENTED** [review]
nice logo

**Comment by PastaShock** [comment]
Thanks Ben!

**Review by PastaShock — APPROVED** [review]
Looks Good Ben!

**Pull request merged**
