### PR TITLE
Visual assets

### LINKED ISSUE #9: Create Logo for App
Create a logo that embodies the use-case for the app.

### LINKED ISSUE #10: Create assets for the page based on the wireframe
In the wireframe there are some images that need to be broken out into rough-draft assets.

### LINKED ISSUE #24: create wireframe for the modal
Create a wireframe in illustrator to give a visual representation of the modal's appearance and functionality.

### PR DESCRIPTION
**Pull request by PastaShock**
Created Assets for the app. These are subject to change but they match the wireframe.

### CODE REVIEW

**Review by corhydare — APPROVED** [review]
looks awesome

**Comment by molano1979** [comment]
Reviewed

**Comment by molano1979** [comment]
Reviewed

**Review by molano1979 — COMMENTED** [review]
Reviewed

**Review by molano1979 — COMMENTED** [review]
Reviewed

**Review by molano1979 — COMMENTED** [review]
Reviewed

**Comment by molano1979** [comment]
Reviewed

**Review by molano1979 — COMMENTED** [review]
Reviewed

**Pull request merged**
